#!/usr/bin/env python3
"""
CRAP Factor Analysis (Change Risk Anti-Patterns)

Combines cyclomatic complexity (radon) with test coverage (coverage.py)
to identify functions that are both complex AND poorly tested.

Formula: CRAP(m) = comp(m)² × (1 - cov(m)/100)³ + comp(m)

Thresholds:
  CRAP ≤  5  → Clean
  CRAP  5-30 → Acceptable
  CRAP > 30  → Needs refactoring or more tests

Usage:
  1. pytest --ignore=scripts --cov=app --cov-report=json -q
  2. python scripts/crap_check.py [--threshold 30]

Requires: radon, coverage.json (generated by pytest-cov)
"""
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


def get_radon_data(source_dir: str) -> dict[str, list[dict[str, Any]]]:
    """Run radon and return per-file complexity data."""
    result = subprocess.run(
        ["radon", "cc", source_dir, "-j"],
        capture_output=True, text=True, check=True,
    )
    return json.loads(result.stdout)


def load_coverage(coverage_path: str) -> dict[str, Any]:
    """Load coverage.json generated by pytest-cov."""
    with open(coverage_path) as f:
        return json.load(f)


def function_coverage(
    executed_lines: set[int],
    missing_lines: set[int],
    func_start: int,
    func_end: int,
) -> float:
    """Calculate coverage % for a specific function's line range."""
    func_executed = {ln for ln in executed_lines if func_start <= ln <= func_end}
    func_missing = {ln for ln in missing_lines if func_start <= ln <= func_end}
    total = len(func_executed) + len(func_missing)
    if total == 0:
        return 100.0  # No statements → fully covered
    return (len(func_executed) / total) * 100


def crap_score(complexity: int, coverage_pct: float) -> float:
    """CRAP(m) = comp² × (1 - cov/100)³ + comp"""
    return complexity ** 2 * (1 - coverage_pct / 100) ** 3 + complexity


def extract_functions(blocks: list[dict]) -> list[dict]:
    """Flatten radon output: extract top-level functions and class methods."""
    functions = []
    for block in blocks:
        if block["type"] == "function":
            functions.append(block)
        elif block["type"] == "class":
            for method in block.get("methods", []):
                functions.append(method)
    return functions


def normalize_path(path: str) -> str:
    """Normalize a file path to use OS separators for comparison."""
    return os.path.normpath(path)


def main() -> int:
    parser = argparse.ArgumentParser(description="CRAP factor analysis")
    parser.add_argument(
        "--threshold", type=float, default=25.0,
        help="CRAP score threshold — functions above this fail (default: 25)",
    )
    parser.add_argument(
        "--coverage-json", default="coverage.json",
        help="Path to coverage.json (default: coverage.json)",
    )
    parser.add_argument(
        "--source-dir", default="app",
        help="Source directory to analyze (default: app)",
    )
    parser.add_argument(
        "--top", type=int, default=20,
        help="Show top N worst functions (default: 20)",
    )
    args = parser.parse_args()

    if not Path(args.coverage_json).exists():
        print(f"ERROR: {args.coverage_json} not found.")
        print("Run: pytest --ignore=scripts --cov=app --cov-report=json -q")
        return 2

    # Gather data
    radon_data = get_radon_data(args.source_dir)
    coverage_data = load_coverage(args.coverage_json)

    # Build coverage lookup: normalized path → (executed, missing)
    cov_lookup: dict[str, tuple[set[int], set[int]]] = {}
    for filepath, fdata in coverage_data.get("files", {}).items():
        norm = normalize_path(filepath)
        cov_lookup[norm] = (
            set(fdata.get("executed_lines", [])),
            set(fdata.get("missing_lines", [])),
        )

    # Calculate CRAP for every function
    results: list[tuple[float, str, str, int, float]] = []  # (crap, file, name, cc, cov%)

    for filepath, blocks in radon_data.items():
        norm = normalize_path(filepath)
        executed, missing = cov_lookup.get(norm, (set(), set()))

        for func in extract_functions(blocks):
            cc = func["complexity"]
            name = func.get("classname", "") + "." + func["name"] if func.get("classname") else func["name"]
            start = func["lineno"]
            end = func["endline"]

            cov_pct = function_coverage(executed, missing, start, end)
            score = crap_score(cc, cov_pct)

            results.append((score, filepath, name, cc, cov_pct))

    # Sort worst first
    results.sort(key=lambda r: r[0], reverse=True)

    # Report
    failures = [r for r in results if r[0] > args.threshold]

    print()
    print("=" * 80)
    print(f"  CRAP Factor Analysis - threshold: {args.threshold}")
    print(f"  Functions analyzed: {len(results)}")
    print(f"  Functions above threshold: {len(failures)}")
    print("=" * 80)

    if results:
        print()
        shown = results[:args.top]
        print(f"  Top {len(shown)} worst CRAP scores:")
        print(f"  {'CRAP':>8}  {'CC':>3}  {'Cov%':>5}  Function")
        print(f"  {'-' * 8}  {'-' * 3}  {'-' * 5}  {'-' * 50}")
        for score, filepath, name, cc, cov_pct in shown:
            flag = " !" if score > args.threshold else ""
            short_path = filepath.replace("\\", "/")
            print(f"  {score:8.1f}  {cc:3d}  {cov_pct:5.1f}  {short_path}::{name}{flag}")

    print()

    if failures:
        print(f"FAILED: {len(failures)} functions exceed CRAP threshold of {args.threshold}")
        return 1
    else:
        print(f"PASSED: All functions below CRAP threshold of {args.threshold}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
